---
title: Setting up myblog
author: Owen Beelders
date: '2020-05-16'
slug: setting-up-myblog
categories: []
tags: []
---

After much trial-and-error, I found that the following steps worked best for me on a Windows machine once my github account had been set up:

1. Run through Chapters 1 - 14 of  [happygitwithr.com](https://happygitwithr.com/new-github-first.html) and ensure that RStudio can connect to your github account. 
2. Implement chapter 15 of  [happygitwithr.com](https://happygitwithr.com/new-github-first.html). Chapter 15 shows you how to set up a github folder for your site, clone it and open the R project for the site in the cloned directory. This makes the connection between RStudio and github seamless.
3. I am hosting via [netlify](netlify.com). Netlify has button, "New site from Git" that does exactly that. Once the website has been updloaded to github, you can use the "production deploys" section to deploy the site.  Steps 2 and 3 ensure that the creation of a post, uploading to github, linking to netlify and then deploying the site is seamless.


Notes:
I reviewed this post by Rob Hyndman [Converting to blogdown](https://robjhyndman.com/hyndsight/blogdown/) and the link to [amber.rbind.io](https://amber.rbind.io/2016/12/19/website/) but found it too technical. (This is more a reflection of my lack of expertise). The list of blogdown functions is useful and it made me go back to [blogdown](https://bookdown.org/yihui/blogdown/) and actually read the text, which turned out to be very useful. The [Tweak your website](https://daijiang.name/en/2017/03/30/updating-website-with-hugo-and-blogdown/) had useful information. 